---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "splunk.fullname" . }}-defaults
  labels:
{{ include "splunk.labels" . | indent 4 }}
data:
  default.yml: |
  {{- with .Values.splunk.defaultYml }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

---

# Now we'll create a bunch of configMaps for all the individual
# folders which makeup a splunk app... which sucks.

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "splunk.fullname" . }}-rfc5424-default
  labels:
{{ include "splunk.labels" . | indent 4 }}
data:
{{ (.Files.Glob "splunk-apps/rfc5424/default/*").AsConfig | indent 2 }}

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "splunk.fullname" . }}-rfc5424-local
  labels:
{{ include "splunk.labels" . | indent 4 }}
data:
{{ (.Files.Glob "splunk-apps/rfc5424/local/*").AsConfig | indent 2 }}

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "splunk.fullname" . }}-rfc5424-lookups
  labels:
{{ include "splunk.labels" . | indent 4 }}
data:
{{ (.Files.Glob "splunk-apps/rfc5424/lookups/*").AsConfig | indent 2 }}

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "splunk.fullname" . }}-rfc5424-metadata
  labels:
{{ include "splunk.labels" . | indent 4 }}
data:
{{ (.Files.Glob "splunk-apps/rfc5424/metadata/*").AsConfig | indent 2 }}
