---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "splunk.fullname" . }}-defaults
  labels:
{{ include "splunk.labels" . | indent 4 }}
data:
  default.yml: |
  {{- with .Values.splunk.defaultYml }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
