{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "splunk.serviceAccountName" . }}
  labels:
{{ include "splunk.labels" . | indent 4 }}
{{- end -}}
