version: "2"

env:
  KUBECONFIG:
    sh: kind get kubeconfig-path

tasks:
  create-kind:
    cmds:
      - kind create cluster --config ci/bootstrap/kind.config.yaml
      - kubectl apply -f ci/bootstrap/rbac.tiller.yml
      - helm init --service-account tiller

  delete-kind:
    cmds:
      - kind delete cluster
      - docker system prune --all --volumes --force

  forwarder-logs:
    cmds:
      - kubectl -n splunk-forwarders logs -f -lapp.kubernetes.io/instance=splunk-forwarders

  dmc-logs:
    cmds:
      - kubectl -n splunk-dmc logs -f -lapp.kubernetes.io/instance=splunk-dmc

  nginx-logs:
    cmds:
      - kubectl -n nginx-ingress logs -f -lapp=nginx-ingress

  forward:
    cmds:
      - kubectl -n nginx-ingress port-forward svc/nginx-ingress-controller 8080:80 4443:443

  sync:
    dir: ci
    cmds:
      - helmfile sync

  template:
    dir: ci
    cmds:
      - helmfile template

  test:
    cmds:
      - helm test splunk-forwarders --cleanup --logs

  release:
    cmds:
      - helm package splunk --destination docs
      - helm repo index docs --url https://aegershman.github.io/splunk-helm-chart/
