version: "2"

env:
  KUBECONFIG:
    sh: kind get kubeconfig-path

tasks:
  create-kind:
    cmds:
      - kind create cluster --config ci/bootstrap/kind.config.yaml
      - kubectl apply -f ci/bootstrap/rbac.tiller.yml
      - helm init --service-account tiller

  delete-kind:
    cmds:
      - kind delete cluster
      - docker system prune --all --volumes --force

  forward:
    cmds:
      - kubectl -n nginx-ingress port-forward svc/nginx-ingress-controller 8080:80

  sync:
    dir: ci
    cmds:
      - helmfile sync

  template:
    dir: ci
    cmds:
      - helmfile template

  test:
    cmds:
      - helm test splunk --cleanup --logs
