version: "2"

tasks:
  kind-create:
    cmds:
      - kind create cluster --config ci/bootstrap/kind.config.yaml --image kindest/node:v1.15.6
      - kubectl create ns splunk

  kind-delete:
    cmds:
      - kind delete cluster

  logs-splunk:
    cmds:
      - kubectl -n splunk logs -f -lapp.kubernetes.io/instance=splunk-forwarders

  logs-nginx:
    cmds:
      - kubectl -n splunk logs -f -lapp=nginx-ingress

  forward:
    cmds:
      - kubectl -n splunk port-forward svc/nginx-ingress-controller 8080:80 4443:443

  sync:
    dir: ci
    cmds:
      - helmfile sync

  template:
    dir: ci
    cmds:
      - helmfile template

  test:
    cmds:
      - helm -n splunk test splunk-forwarders --logs

  release:
    cmds:
      - helm package splunk --destination docs
      - helm repo index docs --url https://aegershman.github.io/splunk-helm-chart/
