apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk.fullname" . }}
  labels:
{{ include "splunk.labels" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.web.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpBindPort }}
      targetPort: http
      name: http
    - port: 9997
      targetPort: s2s
      name: s2s
    - port: 8088
      targetPort: hec
      name: hec
    - port: 5514
      targetPort: pas-syslog
      name: pas-syslog
  selector:
    app.kubernetes.io/name: {{ include "splunk.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
