splunk:
    defaultYml:
        splunkbase_username: ENC[AES256_GCM,data:idNjCd1Sm+S9+w==,iv:HxQfCFB9RsKJMaTSDJL2OeWAZh/8WSrrPvq/8Jb2j/c=,tag:XHpJoxz5vUFIM2RAOKf/hA==,type:str]
        splunkbase_password: ENC[AES256_GCM,data:Jqf9obWSI1c0E1BPu0FyTCvZ6eGIgglHISGOgITiE3xcNzPtRAVZQ0QzJcvKLYuHlwMZ6XqWDg==,iv:FzZ2DgosQsVDx4370fZLgN/IELtiPmBkjciu5vkszNo=,tag:21yDoldasRVyOD66krmm7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-11-11T02:40:04Z'
    mac: ENC[AES256_GCM,data:4i2z1wa0JtXadJADjuxwH8lSIcyO4M/TjS3rwzFXZROFNn9yw6g5RNvJwJuZcx9yLWfcqY8pbgGhZym8fBS6PwgfMfLu41fXfxwp2nmbYc0cvXIw/FLq4ifT4ot1XTD5IeOaxGXk8zjAKjAX/kam9NjLXcLNZL4z6OBJLixavVk=,iv:GS5OtNV9bjgrrOORPJHJcSmKQf6qOOzJJMVPQS0U5KU=,tag:em39ha1g66hkz21Y+ACYqA==,type:str]
    pgp:
    -   created_at: '2019-11-11T02:40:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8UfoNGH8bXiARAAgdN0NC7ktnUEVW0TiJ3jKch3dqkP50PKhEtWlzEoMnu7
            gudPVVd96gQ8hH3XwOtKwYvf9RaglrcHSPXkDFTdNuYZTvt2NHVLeXAAoRVVA1UY
            UFHWDmWX0Fz8myXBtPe9flRqDsW84mDJXSzVz3q8UrKVnzpJOnq8/24NrsH4K0nA
            jVxQtf2BMqBrmh4TkDw+qfR3FKN2smfRMGqv3C5Q2D/aj7TUe5kJaVMOvnYJLpox
            V8KhET57hnAgxX4TlrWTrcNA5ZmtLV9fcN+VmJNBnCXeMj3J94FMCmBCQpUpIIDy
            wy+1Gc4LkfXGgnQPDgCmdvVaJOwxGHiH/GYtVTiYhQx5/Q/AagXeWyvTZCGK7K8g
            4gKX4Lfv1wwirUTXt4UqB63pO6Ia8NNhS6J36OjfyOoP21WLJTpnqI10Y81EuiRB
            0LcVJW0iuwTrbphqvjecnvGDzKyw8YaP7DvqcVduQvjtES/0jHZFKEkQ5sadCyMQ
            qlUID97/Tiwibs/G809sjS4xWxzBFoFY+KvjrE0Y5DFuVf2/FV8l0lg3hBjr442r
            PfHEix1IpBdNeHnB73j6DgTdQWwcDb8wUaXrH64PbJVCG4QWA7OoMYMD6/qOTQeb
            N6RHXmq0c136BT6BtBBnscRK70svBB9A5sw6pIXyi5+u4ZajyJ4brLlUSdyOys/S
            UQHshlv1N2h+Mwj1MThpV3UwgvB3eZN7CgwbZKUCTJRVXfsWj127lTwvHalQUgRx
            1CjPw3sZyta8WH4UcQOYOQIWxHCQU5CqR8Y85FuiUWugIg==
            =TqUQ
            -----END PGP MESSAGE-----
        fp: 1F5DC61F0741F7CCF79A5A22C8182A589C9A04FB
    unencrypted_suffix: _unencrypted
    version: 3.4.0
