splunk:
    defaultYml:
        splunkbase_username: ENC[AES256_GCM,data:9aaKLxVSR+8Brg==,iv:1bYmVFk/1+Gz33IV57aSX/NGTu/6rzs5K2PZ0wKSzt0=,tag:fOqKdmuJUbeScrwTLsM9QQ==,type:str]
        splunkbase_password: ENC[AES256_GCM,data:kpPdKyoKTQFh88SlpF3iAzKCIXiyKNE1OF9JSvKpTf1LZ1VzgX2wgILZcLffHIRpXIWN0hKqLA==,iv:1cUM5smQvHbq/Z0W/ysMPcn1WWrjf/bu41krlFBUCYU=,tag:dhKt64b3CL/waY56om8CzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-11-10T22:57:01Z'
    mac: ENC[AES256_GCM,data:Hh+WCCpdE8JW9EFKYMRow1ZMpnuZY1qymHoQuUGU/KVWqQmDXvmRDJXAY7OuxpP+ONhWf8y1mqawPj4+QhGSKbNqeVE0mJKBinuvTIKEKMzUgJNXRe+b7xRTJlobsfeUle0oZ/8hGkhTWaJIQ39rsLVuiE8QV48ZPH/ssl+yVdU=,iv:qWTLvG7adCYKB1PWbicXLv44MnJzyzH+cTlAetnLnqQ=,tag:e26y0cfoqWYHNm1oagTT3g==,type:str]
    pgp:
    -   created_at: '2019-11-10T22:57:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8UfoNGH8bXiAQ/9EDt15iHSg7bOU6L3X/+0mSOiNe5hYchqPyhrlhNBvlrA
            LHFX35bOCcWrIY0Uu7xFR7d4vegwj8ybZjBoR+103fQoFgyvyQT0QOmQDZ7gTzoQ
            lWndGdL1N9egMrmUJaexCzGhidUCKi4VxO/I+HJ5AGdh90N7JR0TonDTo7wdb+69
            aBKIYn90OmACp8hyHc/9XDofDBug/wqk6uaqU7F/9TQTaW0IrcXZU5iNXAw+K/18
            4rZZNyaOvejxk9WsQsahCHcffe7ixueJNIxkxhfR249rQw8Dm8dnKgnie7d9f+vS
            eexhWIBH1N8cuET9fS91MHCe/Dbyfd6N7BqO6ZEuEbjtXTNtf4VJ/7+CgiCEtLjA
            7JdPzUJTOIt9NbnT14TDkDmoSkTCwc98YqCdgTzhT+9nCMVMd2NrObVr7lYPVdt9
            29HHjp2RkBlx0G/3oK2R5Ej20FsTv85+4NH9T1wZhcztP4IL08q0/5h3C0QUFez8
            iaUynvXar10Tfgx82O0PYo4yrO2s7KZ8lKocUBSDWzP6ITPWNJf4RlnzZAxkUahD
            v+qHymX5yFGHCTfCjr1JuDeaKzgZIGlzVNchSOBwfm4gKz4QwxdgGI2gCTCtDa5x
            VimBf3giCnjCDWSjLvdYX1RmfHKix8sp/FnfLji+WfUvP6WvfJsEgwFC6R8T4CPS
            UQFxU5eAn9KEiLZaPGw7upADFyrMaNuwwFzZ0OYwd4K/2k/SFNnfe+MiXvgnCCxz
            4bUDuVjAVtXwe3U0iBZv8uPpRHMmAA4q1egXmd8be3kSdA==
            =lx4l
            -----END PGP MESSAGE-----
        fp: 1F5DC61F0741F7CCF79A5A22C8182A589C9A04FB
    unencrypted_suffix: _unencrypted
    version: 3.4.0
