controller:
  replicaCount: 1
  hostNetwork: true
  service:
    type: NodePort
    ## deactivate to save some ports
    enableHttp: true
    enableHttps: true

defaultBackend:
  enabled: false

tcp:
  8089: "splunk-forwarders/splunk-forwarders:8089"
  9997: "splunk-forwarders/splunk-forwarders:9997"
  5514: "splunk-forwarders/splunk-forwarders:5514"
