controller:
  replicaCount: 1
  hostNetwork: true
  service:
    type: NodePort

tcp:
  8000: "splunk/splunk:8000"
  9997: "splunk/splunk:9997"
  8088: "splunk/splunk:8088"
  5514: "splunk/splunk:5514"
