controller:
  replicaCount: 1
  # https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L28-L36
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443

defaultBackend:
  enabled: false

tcp:
  8089: "splunk/splunk-forwarders:8089"
  9997: "splunk/splunk-forwarders:9997"
  5514: "splunk/splunk-forwarders:5514"
