controller:
  replicaCount: 1
  hostNetwork: true
  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443

defaultBackend:
  enabled: false

tcp:
  8089: "splunk/splunk-forwarders:8089"
  9997: "splunk/splunk-forwarders:9997"
  5514: "splunk/splunk-forwarders:5514"
