controller:
  replicaCount: 1
  hostNetwork: true
  service:
    type: NodePort
    ## deactivate to save some ports
    enableHttp: true
    enableHttps: true

defaultBackend:
  enabled: false

tcp:
  8089: "splunk/splunk-deployment-server:8089"
  9997: "splunk/splunk-hec:9997"
  5514: "splunk/splunk-hec:5514"
