helmDefaults:
  kubeContext: kind-kind

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: nginx-ingress
    namespace: splunk
    chart: stable/nginx-ingress
    installed: true
    version: ~1.x.x
    values:
      - config/nginx-ingress/values.yml

  - name: splunk-deployment-server
    namespace: splunk
    chart: ../splunk
    installed: true
    values:
      - config/splunk-deployment-server/values.yml
    secrets:
      - config/splunk-deployment-server/secrets.yaml

  - name: splunk-hec
    namespace: splunk
    chart: ../splunk
    installed: true
    values:
      - config/splunk-hec/values.yml
