helmDefaults:
  kubeContext: kind-kind

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: nginx-ingress
    namespace: nginx-ingress
    chart: stable/nginx-ingress
    installed: true
    version: ~1.x.x
    values:
      - config/nginx-ingress/values.yml

  - name: splunk-forwarders
    namespace: splunk-forwarders
    chart: ../splunk
    installed: true
    force: false
    values:
      - config/splunk-forwarders/values.yml
    secrets:
      - config/splunk-forwarders/secrets.yaml
