replicaCount: 1

revisionHistoryLimit: 2

ingress:
  enabled: true
  hosts:
    - splunk.127.0.0.1.xip.io
  tls:
    - hosts:
        - splunk.127.0.0.1.xip.io

splunk:
  defaultYml:
    splunk:
      role: splunk_deployer
      ## uuidgen
      ## we could also throw this in the secrets.yml
      password: e9f630105cd740e3b0d81439ef821973
